### ISSUE TITLE
Redux Saga eventChannel Help

### ISSUE THREAD

**Issue by codeBelt** [matteoterrinoni/portfolio#1]
If you have time can you help me understand how this works? (From line 45 in your [file](https://github.com/matteoterrinoni/portfolio/blob/68e0e02352886140da5b0927e6e81d174e2f44f5/app/containers/File/saga.js#L45))
```
  const channel = eventChannel(emit => task.on('state_changed', emit));

  yield takeEvery(channel, (s)=>percentage(s, reducer));
```
How does the `task.on` know what do to with the `emit` item with extra code?

I took what you had and got it working in my code below but I would like to know how it works.
```
export default class BeerTapSaga {

    public static* percentage(snapshot: firebase.storage.UploadTaskSnapshot) {
        const progress: number = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        
        yield put(BeerTapAction.addBeerTapImageProgress(progress));
    }

    public static* addBeerTapImage(action: IAction<File>) {
        const file: File = action.payload;

        try {
            const storageRef: firebase.storage.Reference = FirebaseUtility.getStorage().ref(`folder_name/${file.name}`);
            const uploadTask: firebase.storage.UploadTask = storageRef.put(file);

            const channel: Channel<any> = eventChannel((emit) => uploadTask.on(firebase.storage.TaskEvent.STATE_CHANGED, emit) as any);

            yield takeEvery(channel, (snapshot: firebase.storage.UploadTaskSnapshot) => BeerTapSaga.percentage(snapshot));

            yield uploadTask; // Wait for upload to complete

            yield put(BeerTapAction.addBeerTapImageSuccess(uploadTask.snapshot.downloadURL));
        } catch (error) {
            yield put(ErrorAction.requestFailure(error));
        }
    }

}
```

**Comment by matteoterrinoni** [comment]
I'm not pretty sure. I can assure that task.on is part of [Redux Saga Firebase](https://github.com/n6g7/redux-saga-firebase) a saga library written specifically to work with firebase, and in this case with [Firebase Upload task] (https://firebase.google.com/docs/reference/js/firebase.storage.UploadTask).
Anyway I think item is a callback to the next state of the event stream; so it's used by task on to retrieve all snapshots about the file uploaded.
I'll point you to the source example [redux saga firebase page](https://n6g7.github.io/redux-saga-firebase/reference/storage#uploadFile). Hope it'd be more helpful than me

**Comment by codeBelt** [comment]
Thanks, it's weird that it is working for me because I am not using redux-saga-firebase. I found a course https://www.pluralsight.com/courses/redux-saga that talks about event channels. I will check that out to understand event channels more.
